spring:
  application:
    name: eureka-discovery-service
  security:
    user:
      name: ${EUREKA_USER}
      password: ${EUREKA_PWD}
      roles: SYSTEM


server:
  port: 8888
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8888/eureka
